spring:
  application:
    name: config-demo
#  profiles:
#    active: dev

build:
  id: 10101
  version: 10.2.3
  name: "Application"
  type: "Application Build"


#build:
#  id: ${ID:defaultId}
#  version: ${VERSION:defaultVersion}
#  name: ${NAME:defaultName}



#build:
#  id: ${ID}
#  version: ${VERSION}
#  name: ${NAME}
#  type: ${TYPE}

#  BUILD_ID=4444;BUILD_NAME=NAME_TEST;BUILD_VERSION=1.0.0
# ID=9999;NAME=NEW_NAME;VERSION=3.3.3.3:
